name: mol-tdl
channels:
  - conda-forge
  - pytorch
  - rdkit
dependencies:
  - python=3.10
  - pip=23.2.1
  - numpy=1.24.3
  - scipy=1.10.1
  - pandas=2.0.3
  - scikit-learn=1.3.1
  - networkx=3.1
  - matplotlib=3.6.2
  - pyyaml=6.0
  - tqdm=4.65.0
  - tensorboard=2.12.1
  - rdkit
  - gudhi=3.10.1
  - dgl=2.1.0
  - ogb=1.3.6
  - pip:
      # Core DL stack
      - torch==1.13.1
      - torchvision==0.16.0+cpu     
      - torchaudio==2.1.0+cpu

      # PyTorch Geometric core
      - torch-geometric==2.6.0

      
      - torch-scatter==2.1.0+pt113cu116
      - torch-sparse==0.6.15+pt113cu116
      - torch-cluster==1.6.0+pt113cu116
      - torch-spline-conv==1.2.1+pt113cu116

      
      - transformers==4.34.0
      - tokenizers==0.14.1
      - huggingface-hub==0.17.3
      - GraphRicciCurvature==0.5.3.2
      - umap-learn==0.5.7
      - pot==0.9.4
      - littleutils==0.2.4
      - hickle==5.0.3
      - reportlab==3.6.12
      - python-louvain==0.16
      - requests==2.31.0
      - httpx==0.25.2
      - anyio==4.1.0
      - pydantic==2.10.6
      - pydantic_core==2.27.2
      - Flask==3.0.3
      - Flask-Assets==2.1.0
      - webassets==2.0
